/*
  MatematikaPakADe — Bank soal untuk CBT (questions.js)
  Notasi matematika ditulis dalam teks biasa (°, √, ², ³, π, ∠)
  supaya bisa dipakai langsung di form ujian tanpa perlu KaTeX.
*/

const QUESTION_BANK = [
  {
    id: 'q1',
    topic: 'Garis & Sudut',
    text: 'Dua sudut saling berpelurus. Jika salah satu sudutnya 65°, besar sudut pasangannya adalah...',
    options: ['105°', '115°', '125°', '135°'],
    correct: 1,
    explain: 'Berpelurus berarti berjumlah 180°: 180° − 65° = 115°.',
  },
  {
    id: 'q2',
    topic: 'Segitiga',
    text: 'Segitiga ABC memiliki sudut luar di C sebesar 110°. Jika ∠A = 40°, maka ∠B adalah...',
    options: ['60°', '65°', '70°', '75°'],
    correct: 2,
    explain: 'Sudut luar = jumlah dua sudut dalam yang tidak berpelurus dengannya: 110° = 40° + ∠B ⇒ ∠B = 70°.',
  },
  {
    id: 'q3',
    topic: 'Segitiga',
    text: 'Titik G adalah titik berat segitiga ABC. Jika panjang median dari A adalah 18, panjang AG adalah...',
    options: ['6', '9', '12', '15'],
    correct: 2,
    explain: 'Rasio AG:GM = 2:1, sehingga AG = (2/3) × 18 = 12.',
  },
  {
    id: 'q4',
    topic: 'Lingkaran',
    text: 'Lingkaran berjari-jari 10 memiliki tali busur AB sepanjang 12. Jarak pusat lingkaran ke tali busur AB adalah...',
    options: ['6', '7', '8', '9'],
    correct: 2,
    explain: 'Setengah tali busur = 6. Jarak = √(10² − 6²) = √64 = 8.',
  },
  {
    id: 'q5',
    topic: 'Lingkaran',
    text: 'Segiempat tali busur ABCD memiliki ∠A = 80°. Besar ∠C adalah...',
    options: ['80°', '90°', '100°', '110°'],
    correct: 2,
    explain: 'Sudut berhadapan pada segiempat tali busur berjumlah 180°: 180° − 80° = 100°.',
  },
  {
    id: 'q6',
    topic: 'Bangun Datar',
    text: 'Segitiga ABC memiliki sisi a=7, b=8, c=9. Luasnya (rumus Heron) adalah...',
    options: ['10√5', '12√5', '14√5', '16√5'],
    correct: 1,
    explain: 's = 12. Luas = √(12×5×4×3) = √720 = 12√5.',
  },
  {
    id: 'q7',
    topic: 'Bangun Datar',
    text: 'Dua lingkaran berjari-jari 8 dan 3, jarak antar pusat 13. Panjang garis singgung persekutuan luarnya adalah...',
    options: ['9', '10', '11', '12'],
    correct: 3,
    explain: '√(13² − (8−3)²) = √(169−25) = √144 = 12.',
  },
  {
    id: 'q8',
    topic: 'Segitiga',
    text: 'Segitiga siku-siku ABC siku-siku di C, dengan AC=9 dan BC=12. Jari-jari lingkaran dalamnya adalah...',
    options: ['2', '3', '4', '5'],
    correct: 1,
    explain: 'AB = √(9²+12²) = 15. r = (9+12−15)/2 = 3.',
  },
  {
    id: 'q9',
    topic: 'Vektor',
    text: 'Diketahui vektor a=(3,4) dan b=(−4,3). Sudut antara vektor a dan b adalah...',
    options: ['45°', '60°', '90°', '120°'],
    correct: 2,
    explain: 'a·b = 3(−4)+4(3) = 0, sehingga a tegak lurus b (90°).',
  },
  {
    id: 'q10',
    topic: 'Vektor',
    text: 'Diketahui A(2,3) dan B(6,7). Panjang vektor AB adalah...',
    options: ['2√2', '4√2', '4√3', '6√2'],
    correct: 1,
    explain: 'AB = (4,4). |AB| = √(16+16) = √32 = 4√2.',
  },
  {
    id: 'q11',
    topic: 'Transformasi',
    text: 'Titik (3,5) direfleksikan terhadap sumbu-x. Bayangannya adalah...',
    options: ['(3,5)', '(3,−5)', '(−3,5)', '(−3,−5)'],
    correct: 1,
    explain: 'Refleksi terhadap sumbu-x: (x,y) → (x,−y), jadi (3,−5).',
  },
  {
    id: 'q12',
    topic: 'Transformasi',
    text: 'Titik (2,4) dirotasi 90° berlawanan arah jarum jam terhadap titik asal. Bayangannya adalah...',
    options: ['(4,2)', '(−4,2)', '(4,−2)', '(−4,−2)'],
    correct: 1,
    explain: 'Rotasi 90°: (x,y) → (−y,x), jadi (−4,2).',
  },
  {
    id: 'q13',
    topic: 'Transformasi',
    text: 'Titik (1,2) didilatasi dengan pusat O dan faktor skala 3. Bayangannya adalah...',
    options: ['(3,5)', '(3,6)', '(4,5)', '(4,6)'],
    correct: 1,
    explain: 'Dilatasi pusat O faktor k: (x,y) → (kx,ky) = (3,6).',
  },
  {
    id: 'q14',
    topic: 'Dimensi Tiga',
    text: 'Kubus memiliki panjang rusuk 8 cm. Panjang diagonal ruangnya adalah...',
    options: ['6√3 cm', '7√3 cm', '8√3 cm', '9√3 cm'],
    correct: 2,
    explain: 'Diagonal ruang kubus = s√3 = 8√3 cm.',
  },
  {
    id: 'q15',
    topic: 'Dimensi Tiga',
    text: 'Balok berukuran 3×4×12 cm. Panjang diagonal ruangnya adalah...',
    options: ['11 cm', '12 cm', '13 cm', '14 cm'],
    correct: 2,
    explain: '√(3²+4²+12²) = √(9+16+144) = √169 = 13 cm.',
  },
  {
    id: 'q16',
    topic: 'Dimensi Tiga',
    text: 'Kubus ABCD.EFGH memiliki rusuk 6 cm. Jarak titik A ke bidang diagonal BDG adalah...',
    options: ['√3 cm', '2√3 cm', '3√3 cm', '4√3 cm'],
    correct: 1,
    explain: 'Jarak = s√3/3 = 6√3/3 = 2√3 cm.',
  },
  {
    id: 'q17',
    topic: 'Segitiga',
    text: 'Segitiga ABC memiliki AB=7, AC=9, dan BC=8. Panjang median dari A ke BC (Teorema Apollonius) adalah...',
    options: ['6', '7', '8', '9'],
    correct: 1,
    explain: 'BD=DC=4. AB²+AC² = 2(AD²+BD²) ⇒ 49+81 = 2(AD²+16) ⇒ AD²=49 ⇒ AD=7.',
  },
  {
    id: 'q18',
    topic: 'Segitiga',
    text: 'Pada segitiga ABC, DE ∥ BC dengan D pada AB, E pada AC. Jika AD=4, DB=6, dan AC=15, panjang AE adalah...',
    options: ['5', '6', '7', '8'],
    correct: 1,
    explain: 'AD/DB = AE/EC ⇒ 4/6 = AE/(15−AE) ⇒ 60 = 10AE ⇒ AE = 6.',
  },
];
